### ISSUE TITLE
Outdated default python settings?

### ISSUE THREAD

**Issue by Abildtoft** [smart-on-fhir/fhir-parser#10]
When using the settings.py, as directed, from the "Python" folder, line 590 in fhirspec.py:

`type_code = self.profile.spec.settings.default_base.get(self.profile.structure.kind)`

Produces an error as settings.py (from the "Python" folder) has no attribute 'default_base'. Adding:

```default_base = {
    'contained': 'FHIRElement',
    'resource': 'FHIRResource'
}```

To settings.py allows the parser to run without issue. This mirrors the Swift settings.py, but I'm enough of a FHIR newbie that I cannot fully comprehend whether or not that has any unwelcomed consequences.

**Comment by p2** [comment]
Yes, you're right that these are missing and that the parser runs if you apply changes, as you suggest. However, `FHIRElement` must be updated to make it work on master (and probably renamed as it is in Swift). Models generated on latest master will all fail on contained resources.
