### ISSUE TITLE
Support for Extensions

### ISSUE THREAD

**Issue by qcastellanos** [smart-on-fhir/fhir-parser#16]
Hello,
I've been looking into how to use fhir-parser for generating Swift objects (looked at Swift-FHIR already). I was wondering if fhir-parser currently supports extensions of FHIR models and how that works? And if not, what would be required to support them?

Thanks,
Quyen
quyen.castellanos@parivedasolutions.com

**Comment by p2** [comment]
If you're using the Swift library you can use [`extensions(forURI:)`](https://github.com/smart-on-fhir/Swift-FHIR/blob/master/Sources/Client/Element%2BExtensions.swift) on any resource or element.
