### ISSUE TITLE
Element ordering

### ISSUE THREAD

**Issue by hsolbrig** [smart-on-fhir/fhir-parser#27]
The elements in the emitted json objects are alphabetized and, as such, are not valid input to a FHIR server

**Comment by mikix** [comment]
Can you expand on this / provide an example of invalid input?

JSON element order is not guaranteed, and [the spec notes](https://www.hl7.org/fhir/json.html) that "Properties can appear in any order" and also that in the [canonical form](https://www.hl7.org/fhir/json.html#canonical) properties SHALL be alphabetical.

So I'm going to optimistically close this as "working as intended" but please re-open if I've misunderstood / there's more to do here.
