### ISSUE TITLE
Enable Travis repo

### ISSUE THREAD

**Issue by palfrey** [smart-on-fhir/fhir-parser#45]
@raheelsayeed Now that #43 is merged, can you enable https://travis-ci.com/github/smart-on-fhir/fhir-parser please? (and fix the build badge so it stops pointing to my repo)

**Comment by palfrey** [comment]
@p2-apple @jmandel Can either of you fix this one?

**Comment by palfrey** [comment]
Or plausibly replace it with say Github Actions now Travis is kinda terrible. Thoughts anyone?

**Comment by mikix** [comment]
Good idea - plus that way they can be integrated as required tests for PRs.

Got a PR to do this above.
