### ISSUE TITLE
exception about copying a file

### ISSUE THREAD

**Issue by tisdall** [smart-on-fhir/fhir-parser#7]
```
INFO:fhirparser:Copying manual profiles in __init__.py to ../models/__init__.py
Traceback (most recent call last):
  File "generate.py", line 25, in <module>
    spec.write()
  File "/home/tim/fhir-parser/fhirspec.py", line 216, in write
    renderer.copy_files()
  File "/home/tim/fhir-parser/fhirrenderer.py", line 60, in copy_files
    shutil.copyfile(filepath, tgt)
  File "/home/tim/fhir-parser/env/lib/python3.4/shutil.py", line 109, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../models/__init__.py'
```

I'm not sure what's going on here...  I had put in a hack to get around the issue in #6 and then I hit this exception.

**Comment by tisdall** [comment]
ah..  I see now that it's in the `settings.py`.  This is probably something to add to the README since no one will have a `models` directory created one step up from their git clone of this repo.

**Comment by tisdall** [comment]
It might be a good idea to just have an empty `models` directory in this repo and point the settings files at it.

**Comment by p2** [comment]
Not sure about an empty `models` directory since that is not useful, you want to create the models somewhere else so you can use them (like we do in [client-py](https://github.com/smart-on-fhir/client-py)). But a more thorough explanation in the README would definitely help.

**Comment by tisdall** [comment]
Okay, that saves me asking the next question about how to use those models...  :)  I'll take a look at client-py!

Perhaps most people come here after looking at client-py, but you may want to add a note in the README to take a look at client-py.

**Comment by p2** [comment]
Yes agreed; the parser was initially part of client-py and then spun out. I definitely have to explain better, I'll keep this open to remind me. :)
