### ISSUE TITLE
validation?

### ISSUE THREAD

**Issue by tisdall** [smart-on-fhir/fhir-parser#8]
Maybe this is more of a question about clarification of function then an actual "issue", but I'm not really sure how to contact you directly...

Do these models perform any sort of validation?

for example:
```
>>> x = models.device.Device({"manufacturer":"me", "wrong":"so so wrong"})
>>> x.as_json()
{'manufacturer': 'me'}
```

If you pass things in that don't map properly they seem to just get dropped instead of throwing an exception.

Also, I found it a little weird that the output of `Device.as_json` didn't automatically add a `'resourceType': 'Device'` and explicitly adding one into the constructor seemed to not change that.

**Comment by p2** [comment]
Deserialization does not yet perform any validation, it just drops invalid keys. Serialization is WiP, I've just started that a few days ago.

There will be validation soon and serialization will also be complete, I have some things in place locally. Forgot to put serialization on the develop branch, it's on the develop branch in client_py... :-/

**Comment by tisdall** [comment]
Ah, yeah, I saw you added the `as_json` just last week but didn't know it was a WIP.  I see there's code setting the `resourceType` based on the object type, but didn't really have time to delve in far enough to see why it didn't end up in the final serialization.

**Comment by p2** [comment]
I've pushed a change to add "resourceType" to resources. No validation yet as I use it as a client library where I don't care if I get data that I don't understand.

**Comment by tisdall** [comment]
slightly off topic...  is there a factory/constructor that you'd pass a dict or json string into that outputs the appropriate type object based on the contents?   (ie you pass in dict with `"contentType":"Device"` in it and you get a `Device()` back out)

**Comment by p2** [comment]
Yes there is. It's implemented in `FHIRElementFactory`:

```python
import fhirelementfactory

device = fhirelementfactory.FHIRElementFactory.instantiate('Device', jsonobj)
device = fhirelementfactory.FHIRElementFactory.instantiate(jsonobj['resourceType'], jsonobj)
```

`FHIRResource` uses it transparently, looking at "resourceType":

```python
import fhirresource

device = fhirresource.FHIRResource.with_json(jsonobj)
```

**Comment by tisdall** [comment]
> No validation yet as I use it as a client library where I don't care if I get data that I don't understand.

For client library, though, you should probably care when doing things like PUT and are sending objects to the server, no?  From a cursory look at client-py it doesn't look like it does that sort of thing yet, any way.

**Comment by p2** [comment]
I pushed create and update earlier today; it only serializes properties it knows, so that should be fine.

**Comment by tisdall** [comment]
I was thinking about validation on elements that are required but missing when serialization is done.  So, for example `type` on a `Device` is a required value.  Right now you can create and serialize a Device object with no `type`.

**Comment by p2** [comment]
Ah I see. Yes, this can be done, `fhir-parser` knows if an element is required or not, it's just not represented in the generated classes yet (it is in Swift). Not sure if it should raise, but at least a warning would be convenient.
