### ISSUE TITLE
No LICENSE file in the repository

### ISSUE THREAD

**Issue by devin-fisher** [smart-on-fhir/fhir-parser#9]
Looking to use this parser but I need to know what LICENSE this code is under so I see if it plays well other software packages.

I see the other repositories on the smart-on-fhir are apache 2.0, maybe this one is too but is just missing the LICENSE file?

**Comment by jmandel** [comment]
Yes, this should be licensed with Apache 2.0. 

@p2 can you make it look like https://github.com/smart-on-fhir/api-server/blob/master/LICENSE ?

**Comment by p2** [comment]
Definitely.

**Comment by devin-fisher** [comment]
thanks.
